export const REALTIMEPREVIEW = 'REALTIMEPREVIEW';
export const FULLPREVIEW = 'FULLPREVIEW';
export const FULLEDITOR = 'FULLEDITOR';
export const DIVIDED = 'DIVIDED';
export const SHORTCUT = 'SHORTCUT';
export const AUTOMATION = 'AUTOMATION';